version: "3.8"

services:
  web:
    image: gif_convertor_image
    ports:
      - "4200:4200"
      - "3000:3000"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1.0"
          memory: 2G
      restart_policy:
        condition: on-failure
    networks:
      - app-network

  worker:
    image: gif_convertor_image
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "1.0"
          memory: 2G
      restart_policy:
        condition: on-failure
    networks:
      - app-network

networks:
  app-network:
    driver: overlay
    attachable: true
